version: "3"
services:
      app:
        container_name: app
        image: deleted2001/auth_service
        restart: always
        # build: api/.
        ports:
          - 8000:8000
        links:
          - mongo
      mongo:
        container_name: mongo
        image: mongo
        volumes:
          - ./data:/data/db
        expose:
          - 27017