apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
  namespace: hash
spec:
  type: NodePort
  ports:
  - name: "auth"
    port: 8000
    targetPort: 8000
    nodePort: 31001
  selector:
    app: auth