apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
  namespace: hash
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: deleted2001/auth_service:latest
        imagePullPolicy: Always
        name: auth
        ports:
        - containerPort: 8000
          name: auth