name: Auth Service CI/CD

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: "Install node 14.16.1"
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'
      - name: "Setup tests"
        run: cd api && npm install && npm uninstall bcrypt && npm i bcrypt && npm test
      
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/auth_service:latest
